package example;

/**
* example/fibonacciHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fibonacci.idl
* miércoles 4 de octubre de 2017 03:48:07 PM COT
*/

public final class fibonacciHolder implements org.omg.CORBA.portable.Streamable
{
  public example.fibonacci value = null;

  public fibonacciHolder ()
  {
  }

  public fibonacciHolder (example.fibonacci initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = example.fibonacciHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    example.fibonacciHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return example.fibonacciHelper.type ();
  }

}
